// <auto-generated />
using System;
using Magic_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240206120406_AddHouseTable")]
    partial class AddHouseTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Magic_VillaAPI.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Aduragbemi",
                            CreatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4937),
                            HouseNumber = 1,
                            Name = "Pool View",
                            Sqft = 3000,
                            UpdatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4951)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Yenusi",
                            CreatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4954),
                            HouseNumber = 2,
                            Name = "Beach View",
                            Sqft = 3200,
                            UpdatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4955)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Aderibigbe",
                            CreatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4958),
                            HouseNumber = 3,
                            Name = "Liverpool View",
                            Sqft = 3500,
                            UpdatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4959)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Crescent",
                            CreatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4961),
                            HouseNumber = 4,
                            Name = "Las-Vegas View",
                            Sqft = 3800,
                            UpdatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4962)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Aduragbemi",
                            CreatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4965),
                            HouseNumber = 5,
                            Name = "Alaska View",
                            Sqft = 4000,
                            UpdatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4966)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Aduragbemi",
                            CreatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4968),
                            HouseNumber = 6,
                            Name = "Manchester View",
                            Sqft = 4500,
                            UpdatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4969)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Aduragbemi",
                            CreatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4971),
                            HouseNumber = 7,
                            Name = "Lagoon View",
                            Sqft = 4600,
                            UpdatedTime = new DateTime(2024, 2, 6, 13, 4, 6, 17, DateTimeKind.Local).AddTicks(4972)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
